# Basic linear algebra in Julia
Author: Andreas Noack Jensen (MIT & JuliaComputing) (https://twitter.com/anoackjensen?lang=en)
(with edits from Jane Herriman)

First let's define a random matrix

In [1]:
A = rand(1:4,3,3)

3×3 Matrix{Int64}:
 4  4  1
 4  3  1
 4  2  3

Define a vector of ones

In [2]:
x = fill(1.0, (3,)) # = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

Notice that $A$ has type Array{Int64,2} but $x$ has type Array{Float64,1}. Julia defines the aliases Vector{Type}=Array{Type,1} and Matrix{Type}=Array{Type,2}. 

Many of the basic operations are the same as in other languages
#### Multiplication

In [3]:
b = A*x

3-element Vector{Float64}:
 9.0
 8.0
 9.0

#### Transposition
As in other languages `A'` is the conjugate transpose, or adjoint

In [4]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 4  4  4
 4  3  2
 1  1  3

and we can get the transpose with

In [5]:
transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 4  4  4
 4  3  2
 1  1  3

#### Transposed multiplication
Julia allows us to write this without *

In [6]:
A'A

3×3 Matrix{Int64}:
 48  36  20
 36  29  13
 20  13  11

#### Solving linear systems 
The problem $Ax=b$ for ***square*** $A$ is solved by the \ function.

In [7]:
A\b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

`A\b` gives us the *least squares solution* if we have an overdetermined linear system (a "tall" matrix)

In [8]:
Atall = rand(3, 2)

3×2 Matrix{Float64}:
 0.619717  0.40685
 0.120604  0.609795
 0.835362  0.207697

In [9]:
Atall\b

2-element Vector{Float64}:
  7.65860430758066
 11.345581820030544

and the *minimum norm least squares solution* if we have a rank-deficient least squares problem

In [10]:
v = rand(3)
rankdef = hcat(v, v)

3×2 Matrix{Float64}:
 0.261366   0.261366
 0.861041   0.861041
 0.0691151  0.0691151

In [11]:
?hcat

search: hcat hvcat hvncat MathConstants @threadcall catch_backtrace



```
hcat(A...)
```

Concatenate along dimension 2.

# Examples

```jldoctest
julia> a = [1; 2; 3; 4; 5]
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> b = [6 7; 8 9; 10 11; 12 13; 14 15]
5×2 Matrix{Int64}:
  6   7
  8   9
 10  11
 12  13
 14  15

julia> hcat(a,b)
5×3 Matrix{Int64}:
 1   6   7
 2   8   9
 3  10  11
 4  12  13
 5  14  15

julia> c = ([1; 2; 3], [4; 5; 6])
([1, 2, 3], [4, 5, 6])

julia> hcat(c...)
3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

julia> x = Matrix(undef, 3, 0)  # x = [] would have created an Array{Any, 1}, but need an Array{Any, 2}
3×0 Matrix{Any}

julia> hcat(x, [1; 2; 3])
3×1 Matrix{Any}:
 1
 2
 3
```


In [12]:
rankdef\b

2-element Vector{Float64}:
 6.054570099137534
 6.054570099137534

Julia also gives us the minimum norm solution when we have an underdetermined solution (a "short" matrix)

In [13]:
bshort = rand(2)
Ashort = rand(2, 3)

2×3 Matrix{Float64}:
 0.183632  0.25707   0.252801
 0.697986  0.136016  0.800307

In [13]:
Ashort\bshort

3-element Vector{Float64}:
 -4.139674407706176
 -0.9797338415813472
 23.563074056363842

# The LinearAlgebra library

While much of linear algebra is available in Julia by default (as shown above), there's a standard library named `LinearAlgebra` that brings in many more relevant names and functions. In particular, it provides factorizations and some structured matrix types.  As with all packages, you can bring these additional features into your session with a `using LinearAlgebra`.

### Exercises

#### 10.1 
Take the inner product (or "dot" product) of a vector `v` with itself and assign it to variable `dot_v`.



In [22]:
using LinearAlgebra

In [14]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [23]:
dot_v = dot(v, v)

14

In [24]:
@assert dot_v == 14

#### 10.2 
Take the outer product of a vector v with itself and assign it to variable `outer_v`

In [25]:
outer_v = kron(v,v)

9-element Vector{Int64}:
 1
 2
 3
 2
 4
 6
 3
 6
 9

In [18]:
@assert outer_v == [1 2 3
                    2 4 6
                    3 6 9]

#### 10.3 
Use [LinearAlgebra.cross](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.cross) to compute the cross product of a vector v with itself and assign it to variable `cross_v`

In [21]:
@assert cross_v == [0, 0, 0]